[build]
  command = "cd juco-time-source/juco-time && npm install && npm run build"
  publish = "juco-time-source/juco-time/dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
